---
- name: Set global default editor to vim | Rhel
  lineinfile:
    dest: '/etc/profile.d/vim.sh'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: EOF
  with_items:
    - { regexp: '^export VISUAL="vim"', line: 'export VISUAL="vim"' }
    - { regexp: '^export EDITOR="vim"', line: 'export EDITOR="vim"' }
  when: ansible_os_family == 'RedHat' and vim_default_editor

  # Debian does this by default
- name: Adding source vimrc.local for Rhel family | Rhel
  lineinfile:
    state: present
    dest: '/etc/vimrc'
    insertafter: EOF
    line: 'source /etc/vim/vimrc.local'
  when: ansible_os_family == 'RedHat'
