---
- stat: path=/etc/alternatives/editor
  register: editor
  when: ansible_os_family == 'Debian' and vim_default_editor

- name: set global default editor to vim on Debian family
  shell: 'update-alternatives --set editor /usr/bin/vim.basic'
  when: ansible_os_family == 'Debian' and not editor.stat.lnk_source == '/usr/bin/vim.basic' and vim_default_editor