---
- import_tasks: "install_Debian.yml"
  when: ansible_os_family == 'Debian'

- import_tasks: "install_RedHat.yml"
  when: ansible_os_family == 'RedHat'

- import_tasks: "config.yml"

- import_tasks: "config_RedHat.yml"
  when: ansible_os_family == 'RedHat'

- import_tasks: "config_Debian.yml"
  when: ansible_os_family == 'Debian'