---
- include_tasks: "install_Debian.yml"
  when: ansible_os_family == 'Debian'

- include_tasks: "install_RedHat.yml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "config.yml"

- include_tasks: "config_RedHat.yml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "config_Debian.yml"
  when: ansible_os_family == 'Debian'
